### ISSUE TITLE
네번째 성능 리포트 - auto scaling

### ISSUE THREAD

**Issue by ppabam** [ppabam/101#81]
- http://jasonwilder.com/blog/2014/03/25/automated-nginx-reverse-proxy-for-docker/
- https://hub.docker.com/r/nginxproxy/nginx-proxy

```yaml
services:
  web1:
    image: httpd:latest
    volumes:
      - ./pyweb1:/usr/local/apache2/htdocs
    deploy:
      resources:
        limits:
          cpus: "0.01" 
          memory: "40M"
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=80
  
  nginx-proxy:
    image: nginxproxy/nginx-proxy # https://github.com/nginx-proxy/nginx-proxy
    ports:
      - "9889:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web1
```
