### ISSUE TITLE
nGrinder 의 Docker 통합

### ISSUE THREAD

**Issue by ppabam** [ppabam/101#83]
```yaml
services:
  controller:
    image: ngrinder/controller
    restart: always
    ports:
      - "9000:80"
      - "16001:16001"
      - "12000-12009:12000-12009"
    volumes:
      - ./ngrinder-controller:/opt/ngrinder-controller
    links:
      - web1

  agent:
    image: ngrinder/agent
    restart: always
    links:
      - controller
      - web1

  web1:
    image: httpd:latest
    volumes:
      - ./pyweb1:/usr/local/apache2/htdocs
    deploy:
      resources:
        limits:
          cpus: "0.01"
          memory: "40M"
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=172.17.0.1,localhost,127.0.0.1
      - VIRTUAL_PORT=80

  nginx-proxy:
    image: nginxproxy/nginx-proxy # https://github.com/nginx-proxy/nginx-proxy
    ports:
      - "8083:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web1 
```
