### ISSUE TITLE
여섯번째 성능 리포트 - 캐싱

### ISSUE THREAD

**Issue by ppabam** [ppabam/101#86]
- docker compose down
- git push, branch 생성 및 이동
- docker-compose.yml 에 8083 으로 되어 있는 포트를 8949로 변경
- nginx-proxy 이름을 lb 로 변경
- docker-compose.yml 에 아래 키싱 서버 추가
```yaml
  cache:
    image: nginx
    ports:
      - "8083:80"
    volumes:
      - ./conf/cache/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - lb
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "20M"
```

```bash
$ cat ./conf/cache/default.conf
proxy_cache_path /etc/nginx/cache levels=1:2 keys_zone=my_cache:10m max_size=100m inactive=1m use_temp_path=off;
log_format cache '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" cs=$upstream_cache_status';

server {
    listen 80;
    server_name 172.17.0.1 localhost 127.0.0.1;

    ## Access and error logs.
    access_log /var/log/nginx/api-proxy.access.log cache;
    error_log  /var/log/nginx/api-cache.error.log;

    location / {
        proxy_pass http://172.17.0.1:8949/;

        # proxy_ignore_headers X-Accel-Expires Expires Cache-Control;
        proxy_cache_valid 200 302 1m;
        proxy_cache_valid 404 1m;

        proxy_cache my_cache;
    }
}
```
